on: merge request

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: analysis
      - run: | 
      make packages
      make analysis
  build:
    runs-on: ubuntu-latest
    needs: [analysis]
    steps:
    - uses: actions/checkout@v2 
    - name: build
     - run: | 
     make packages
     make build
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: |
      make packages
      make test