on: push

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make packages && make analysis
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install lcov
  test:
    runs-on: ubuntu-latest
    needs: [analysis]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install lcov